export const SITE = {
  website: "https://manasavinashe.github.io/wretched-wavelength/",
  author: "Manas Avinashe",
  profile: "https://github.com/manasavinashe",
  desc: "Personal projects in finance and computer vision.",
  title: "Manas Avinashe",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit page",
    url: "https://github.com/manasavinashe/wretched-wavelength/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Asia/Kolkata",
} as const;